name: "Consumable Tokens"
description: "Generate Consumable Token for triggering acctions in Home Assistant"
version: "1.0.0"
slug: "consumabletokens"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386