name: "Consumable Tokens"
description: "Generate Consumable Token for triggering acctions in Home Assistant"
version: "1.0.0"
slug: "consumabletokens"
init: false
image: node:alpine
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/mircopergreffi/hassio-addon-consumabletokens
# webui: http://[HOST]:[PORT]/dashboard
startup: before
# boot: manual
ports:
  8081/tcp: 8081
  8082/tcp: 8082

# host_network: true
# host_ipc: false
# hassio_api: false
